const values = {
	USER_CLUB_ROLE_MEMBER: 'M',
	USER_CLUB_ROLE_ADMIN: 'A',
	USER_CLUB_ROLE_FOUNDER: 'F',

	ACTIVITY_STATUS_PENDING: 'P',
	ACTIVITY_STATUS_CANCELED: 'C',
	ACTIVITY_STATUS_FINISHED: 'F',
	ACTIVITY_STATUS_RECRUITING: 'R',

	CLUB_MESSAGE_TYPE_CREATE: 'C',
	CLUB_MESSAGE_TYPE_ACTIVITY: 'A',
	CLUB_MESSAGE_TYPE_ACTIVITY_BILL: 'AB',
	CLUB_MESSAGE_TYPE_BULLETIN: 'B',
	CLUB_MESSAGE_TYPE_ENROLLMENT: 'E',
	CLUB_MESSAGE_TYPE_QUIT: 'Q',
	CLUB_MESSAGE_TYPE_KICK: 'K',

	NOTIFICATION_TYPE_JOIN_CLUB: 'JC',
	NOTIFICATION_TYPE_QUIT_CLUB: 'QC',
	NOTIFICATION_TYPE_KICK_CLUB: 'KC',
	NOTIFICATION_TYPE_ACTIVITY_BILL: 'AB',
	NOTIFICATION_TYPE_ACTIVITY_PAYMENT: 'AP',
	NOTIFICATION_TYPE_ACTIVITY_CREATION: 'AC',
	NOTIFICATION_TYPE_SYSTEM: 'S',
	NOTIFICATION_TYPE_APPLICATION: 'A',
	NOTIFICATION_TYPE_APPLICATION_REJECTION: 'AR',

	APPLICATION_STATUS_UNHANDLED: 'U',
	APPLICATION_STATUS_REJECTED: 'R',
	APPLICATION_STATUS_ACCEPTED: 'A',

	ACTIVITY_BILL_STATUS_UNPUBLISHED: 'U',
	ACTIVITY_BILL_STATUS_PUBLISHING: 'P',
	ACTIVITY_BILL_STATUS_FINISHED: 'F',

};

module.exports = values;
